### ISSUE TITLE
DS 2.5.2 undefined variable.

### ISSUE THREAD

**Issue by rcollette** [PBGUX/bower-designsystem#5] opened 2016-03-18 15:32 UTC
When I upgrade from 2.4 to 2.5.2, our bower post install script is failing with the following error.

```
bower                                     postinstall /Volumes/saas-shipping/saas-shipping-ui/node_modules/node-sass/lib/index.js:277
bower                                     postinstall     var payload = util._extend(new Error(), JSON.parse(err));
bower                                     postinstall                                ^
bower                                     postinstall Error: bower_components/pb-design-system/sass/settings/_mixins.scss
bower                                     postinstall Error: Undefined variable: "$pb-blue".
bower                                     postinstall         on line 33 of bower_components/pb-design-system/sass/settings/_mixins.scss
bower                                     postinstall >>  background-image: linear-gradient(90deg, $pb-blue 0%, $pb-magenta 100%);
bower                                     postinstall    ------------------------------------------^
bower                                     postinstall     at options.error (/Volumes/saas-shipping/saas-shipping-ui/node_modules/node-sass/lib/index.js:277:32)
```

**Comment by nishrana** [comment] 2016-03-18 20:56
I'm pretty sure I exactly know what the issue is. For 2.5 release, DS changed the background gradient to two colors. I got the same error when I tried to update to DS 2.5 which is because of the mixin definition which has now changed.

**Comment by nishrana** [comment] 2016-03-18 20:58
It's in the release note and I was gonna talk to Dan about it if it's breaking any other app.

![image](https://cloud.githubusercontent.com/assets/9932055/13891934/964d1eea-ed2a-11e5-83e2-cebae1ef05eb.png)

**Comment by smlombardi** [comment] 2016-03-18 21:32
This shouldn't be happening.  There never was a mixin (actually, an extend) for this before.  In any event, I compile this sass dozens of times a day without error, so the issue seems to be something missing or out of date in the bower component.

We can also try replacing the variables with their hex colors, which would likely be safer.

**Comment by nishrana** [comment] 2016-03-18 21:44
Here's the error we are seeing in horizon.
![image](https://cloud.githubusercontent.com/assets/9932055/13892911/e9d0daf6-ed30-11e5-9c8a-c3f248e0470e.png)

**Comment by danielcollettepb** [comment] 2016-03-22 16:25
reviewed with @nishrana, the _variables was included after the _mixins, swapping appears to fix the issue (since _mixins needs the _variables). She is testing and will submit an MR. Will close this once validated.

**Comment by nishrana** [comment] 2016-03-22 19:12
:+1:

**Comment by nishrana** [comment] 2016-03-22 21:09
No longer an issue. This was fixed in horizon (See @danielcollettepb's comment)

**Closed** 2016-03-22 21:09 UTC
