### ISSUE TITLE
Images in the `dist/design_system.css` file.

### ISSUE THREAD

**Issue by nickroberts** [PBGUX/bower-designsystem#6] opened 2016-09-06 18:24 UTC
I was trying to add DS to an Angular 2 project generated with `angular-cli`.

I installed via `npm i pb-design-system --save`.

`Webpack` was complaining all over the place about images in the css file:

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/pb-design-system/dist/css/design_system.css
Module not found: Error: Can't resolve '../images/logo-usps.png' in '/Volumes/shaolin-warrior/Workspace/PB/Horizon/sendpro-a2/node_modules/pb-design-system/dist/css'
 @ ./~/css-loader!./~/postcss-loader!./~/pb-design-system/dist/css/design_system.css 6:213015-213049 6:405167-405201
 @ ./~/pb-design-system/dist/css/design_system.css
 @ multi styles
```

I'm not sure these should be references to images like this (USPS logo) in there, for one, and if they are (some make sense, like `ajax-loader.gif`), then we should include them in the distribution :)

**Comment by jrnorrisjr** [comment] 2016-12-06 15:37
I have the same issue so I added both DS and BS CSS files under assets/css and included them in index.html instead of referencing them in angular-cli.json as a work-around.

**Comment by smlombardi** [comment] 2016-12-06 16:07
We have removed these images from the css in 3.1, coming soon.

**Comment by azanov** [comment] 2016-12-16 13:21
The image references are still present in 3.1 which makes the package unusable with webpack. Consider removing all images which do not belong in the basic framework or include them in the package.

I have a React application and want to avoid including the design system styles directly in index.html as a workaround. 

Would be great if you can update it soon.

**Comment by smlombardi** [comment] 2016-12-16 13:41
We finally found it hiding in a mixin.  We will fix it shortly.

**Comment by smlombardi** [comment] 2016-12-20 14:07
Fixed in 3.1.1

**Closed by smlombardi** 2016-12-20 14:07 UTC
Labels: bug

**Comment by azanov** [comment] 2016-12-21 09:10
The issue is still not fixed completely:

```
.slick-loading .slick-list {
    background: #fff url("../images/ajax-loader.gif") center center no-repeat
}
```

**Comment by smlombardi** [comment] 2016-12-21 14:23
This is removed in 3.1.2.  To use Slick you will now need to load and link its own Bower component's CSS and theme file.
