### ISSUE TITLE
Toolbar buttons do not style properly when disabled

### ISSUE THREAD

**Issue by ldaug** [PBGUX/bower-designsystem#17] opened 2017-01-10 15:17 UTC
Button elements inside a toolbar do not grey out when disabled.

![image](https://cloud.githubusercontent.com/assets/7534439/21811494/e818ce30-d71d-11e6-8158-b871977e5e49.png)

**Comment by smlombardi** [comment] 2017-01-10 16:48
This is by design:  The intended pattern for toolbars is to HIDE buttons that are not currently viable.

See https://designsystem.pitneycloud.com/#/table-demo/paging and how buttons for edit and delete only appear when a table row is checked.

**Comment by ldaug** [comment] 2017-01-10 16:53
This is not the pattern being followed by UX in applications such as Spectrum Management console. I will follow what they are doing.

**Comment by smlombardi** [comment] 2017-01-10 17:19
Let us know.  It's the pattern being followed in SendPro and other eCommerce apps.

**Comment by ldaug** [comment] 2017-01-10 17:40
Regardless of the suggested pattern (hide vs disable) I would say that a btn should always be styled properly when it has the disabled attribute. Note that some styles to disable the btn are applied (mouse pointer no longer changes on hover). But the color is not grayed out as expected.

**Comment by smlombardi** [comment] 2017-01-10 17:43
I noticed the examples on the site are incorrectly using `btn-link` instead of `btn-default` for the buttons.  I will fix this.  I will also add a user story for making toolbar buttons have the same states as other `btn-default` buttons.

**Comment by ldaug** [comment] 2017-01-10 17:45
Thanks

**Comment by rcollette** [comment] 2017-02-06 02:12
@smlombardi - The won't fix label can come off of this, correct?   You had shown me a picture of disabled toolbar buttons that you were going to implement.

**Comment by smlombardi** [comment] 2017-02-06 12:03
Yes, it's fixed in 3.2.

**Closed by smlombardi** 2017-02-06 12:03 UTC
Labels: bug
